### ISSUE TITLE
void setTime	// установка времени

### ISSUE THREAD

**Issue by DizzyaKZ** [GyverLibs/microDS3231#2]
Предполагается, что void setTime(int8_t seconds, int8_t minutes, int8_t hours, int8_t date, int8_t month, int16_t year);	// установка времени, использует элементы времени в обратном порядке. Честно говоря, бОльшая часть функций делает как раз наооборот HH:MM:SS

Мне кажется, что было бы логичней следовать этому формату.

**Comment by GyverLibs** [comment]
Каких функций?

**Comment by DizzyaKZ** [comment]
Например  `__TIME__ ` возвращает время в формате `HH:MM:SS`

**Comment by GyverLibs** [comment]
Эта функция не имеет отношения к библиотеке. Более того, это не функция вовсе, а один из макросов компилятора avr gcc. То что порядок задания времени нестандартный я согласен, библиотеку писал другой чел. Но менять что то сейчас уже поздно, будет несовместимость
