### ISSUE TITLE
Определение наличия подключенного датчика

### ISSUE THREAD

**Issue by szabota** [GyverLibs/microDS3231#3]
Не хватает функции для определения подключен ли датчик RTC.

**Comment by szabota** [comment]
Так хорошо работает:

bool isRTCConnected(){
  return(rtc.getMonth()>0 && rtc.getMonth()<=12 && rtc.getDate()>0 && rtc.getDate()<=31);
}

**Comment by GyverLibs** [comment]
Не, там по другому делается. Сегодня залью вечерком

**Comment by szabota** [comment]
Спасибо!
