### ISSUE TITLE
Неправильно устанавливается день месяца

### ISSUE THREAD

**Issue by beeline09** [GyverLibs/microDS3231#7]
Использую версию 2.7 с ESP32 на платформе арудино. Пробую установить 10 месяц 21 число 2022 года. Все устанавливается, но при чтении данных день становится 5.

**Comment by GyverLibs** [comment]
День или день недели? См документацию

**Comment by beeline09** [comment]
Извиняюсь, не придал значения дню недели) Все работает! Спасибо за простую библиотеку)
